<?php
//function jsOnResponse($obj)  
// {  
// echo ' 
// <script type="text/javascript"> 
// window.parent.onResponse("'.$obj.'"); 
//  </script> 
// ';  
// }  
//  
// $dir = 'http://mails.local/img/users/'; // путь к каталогу загрузок на сервере  
// $name = basename($_FILES['loadfile']['name']); 
// echo $name;
// $file = $dir.$name;  
//  
// $success = move_uploaded_file($_FILES['loadfile']['tmp_name'], $file);  
// jsOnResponse("{'filename':'".$name."', 'success':'".$success."'}"); 

$uploaddir = 'C:/xampp1/htdocs/mails/public/img/users/'; 
$file = $uploaddir . basename($_FILES['uploadfile']['name']); 
 
if (move_uploaded_file($_FILES['uploadfile']['tmp_name'], $file)) { 
  echo "success"; 
} else {
	echo "error";
}
?>
