
<?php 
echo	"У вас нет прав для доступа к этой странице";

				mysql_query("SET NAMES 'utf8'");
				if(mysql_query("INSERT INTO mails (text, title, date) VALUES ('" . htmlspecialchars($_POST["x1"]) . "', '" . htmlspecialchars($_POST["x2"]) . "', NOW())")){
					$last_id = mysql_insert_id();
	     					
					echo $last_id;
				}	
				else echo "-2";// Ошибка подключения к БД
			
		
		

	echo	"У вас нет прав для доступа к этой странице";
	
?>

