 <?php 
       if ($this->statys=='1'){
   echo '  <script> scr('.$this->id.'); </script>';
           };
        
        if ((Zend_Auth::getInstance()->getIdentity()->id)==($this->escape($this->otpravitel))) {
             $TBmails = new Application_Model_DbTable_mails(); 
             $otpr= $TBmails->getmails($this->otpravitel,'name');
             $img= $TBmails->getmails($this->polychatel,'image');
             $polych=$TBmails->getmails($this->polychatel,'name');
            ?>
            
           <tr id="msg_tr_<?php echo $this->escape($this->id);?>">
          
       
<td id='d' style="padding:5px;vertical-align:top;">
    <a href="<?php echo $img?>"><img style="width:100px;height:100px;" src="
        <?php echo $img?>"></a></td>
       <td style="padding:10px 10px 0 0; vertical-align: top;">
        <a href=""><nobr><?php echo $polych; ?></nobr></a><br>
        <span><nobr><?php echo $this->escape($this->data);?></nobr></span><br>
       </td>
       <td>
        
        <span> <?php echo $this->escape($this->title);/**/?></span>
        
       </td>
       
       <td>
        
        <p><span class="link-button"  id="link-button" onclick="readMessage(<?php echo "'".$otpr."','".$this->text."','".$this->id."','".$this->title."','otpravi'"; ?>)">Прочитать</span></p>   
       <p><span class="link-button" onclick="writeMessage(<?php echo "'".$polych."','".$this->otpravitel."','".$this->polychatel."','".$this->title."'"; ?>)">Ответить</span></p>
        <p><span class="link-button" onclick="deleteMsg(<?php echo "'".$this->id."'"; ?>);">Удалить</span></p>
       </td>
      </tr> 
      <?php }; ?>